# Generated by Django 6.0.3 on 2026-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipv4', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YtdlpVersion',
        ),
    ]
