# Generated by Django 6.0.3 on 2026-07-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_analyticsdashboard_dailysummary_requestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='city',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='longitude',
        ),
    ]
