# Generated by Django 5.2.10 on 2026-09-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_limit_exception_ips',
            field=models.TextField(blank=True, default='', help_text='Comma or newline-separated IP addresses that are exempt from the YouTube daily download limit.'),
        ),
    ]
